import { Link } from 'react-router-dom'
import Icon from '../Components/Icon'
import tutorial from '../assets/images/rex-tutorial.png'
import '../Styles/instructions.css'
const steps = [
  ['folder','Selecciona un caso','Elige un expediente del terminal central según su dificultad: Fácil, Media o Difícil.'],
  ['file','Examina las evidencias','Inspecciona correos, archivos y registros. Cada evidencia nueva aporta +100 puntos.'],
  ['warning','Detecta anomalías','Contrasta dominios, extensiones y cabeceras. Una apariencia profesional no demuestra autenticidad.'],
  ['bulb','Pistas con precaución','¿Estancado? Rex ofrece hasta dos pistas por caso. Cada pista cuesta 50 puntos.'],
  ['clock','Vigila el cronómetro','Dispones de 3 min en Fácil, 2:30 en Media y 2 min en Difícil. El tiempo continúa al cambiar de pantalla.'],
  ['trophy','Resuelve y sube de rango','Valida las tres deducciones para ganar +300 puntos de bonus y guardar tu resultado en el ranking.'],
]
const ranks = [['Novato Forense','0–499 PTS','green'],['Rastreador de Huellas','500–1,499 PTS','cyan'],['Detective de Asalto','1,500–3,499 PTS','lavender'],['Ciber-Maestro Rex','3,500–5,999 PTS','pink'],['Leyenda Élite Prehistórica','6,000+ PTS','yellow']]
export default function Instructions() {
  return <main id="contenido" className="container page-shell manual-page"><span className="eyebrow">● DOCUMENTACIÓN OFICIAL // AGENCIA DE DETECTIVES DE DINOSAURIOS V2.4</span>
    <div className="manual-heading"><div><span className="tag">GUÍA DE CAMPO OFICIAL</span><h1 className="page-title">Manual del detective:<br /><span className="cyan">Protocolo de</span><br /><span className="lavender">investigación</span></h1><p className="page-intro">Aprende los protocolos forenses, el funcionamiento de las pistas tácticas y cómo evitar el fatídico Game Over en el ciberespacio prehistórico.</p></div><div className="manual-actions"><Link className="button purple" to="/case/001">Probar el tutorial</Link><button className="button secondary" onClick={() => window.print()}>Imprimir / guardar ficha en PDF</button></div></div>
    <section className="manual-section"><span className="eyebrow">FASE 01 // METODOLOGÍA SECUENCIAL</span><h2>El ciclo de investigación <span className="cyan">(6 pasos del detective)</span></h2><div className="steps-grid">{steps.map(([icon,title,text],index) => <article className="surface-card step-card" key={title}><div><span className="tag">PASO // 0{index+1}</span><Icon name={icon} size={26} /></div><h3>{index+1}. {title}</h3><p>{text}</p><small>PROTOCOLO DE LA AGENCIA // REX</small></article>)}</div></section>
    <section className="manual-section"><span className="eyebrow">FASE 02 // ARQUITECTURA FORENSE</span><h2>Elementos clave de la interfaz &amp; mecánicas</h2><div className="mechanics-grid">
      <article className="surface-card"><div className="panel-heading"><Icon name="file" /><h3>Evidencias digitales</h3></div><p>Cada investigación pone a tu disposición cuatro artefactos. Inspecciónalos y contrasta sus detalles antes de emitir un veredicto.</p><div className="mini-grid"><div><strong>Correos phishing</strong><p>Remitentes, cabeceras y autenticación.</p></div><div><strong>Archivos sospechosos</strong><p>Extensión final, hash y registros.</p></div><div><strong>Enlaces señuelo</strong><p>Destino real y dominio oficial.</p></div><div><strong>Credenciales expuestas</strong><p>Accesos, codificación y recuperación.</p></div></div><small className="cyan">Inspeccionar de nuevo no duplica los puntos.</small></article>
      <article className="surface-card"><div className="panel-heading"><Icon name="bulb" /><h3>Sistema de pistas</h3></div><p>Dino Rex lleva una pequeña lupa cibernética lista para señalar indicios discretos. Usa su ayuda cuando no encuentres la relación entre las evidencias.</p><blockquote><strong className="lavender">● DINO REX TRANSMITIENDO:</strong><p>“Mira bien el dominio del remitente. ¿Coincide exactamente con el canal oficial?”</p></blockquote><small className="yellow">DISPONIBILIDAD: 2 PISTAS / CASO · COSTO: −50 PTS CADA UNA</small></article>
      <article className="surface-card"><div className="panel-heading pink"><Icon name="warning" /><h3>Game Over &amp; tiempo</h3></div><p>Dos deducciones incorrectas o el tiempo agotado cierran el caso. Un error resta 50 puntos; la puntuación nunca baja de cero.</p><div className="mini-grid"><div><strong className="pink">Tiempo agotado (00:00)</strong><p>El reloj continúa aunque abras el tablero o salgas a otra pantalla.</p></div><div><strong className="pink">Conclusión incorrecta</strong><p>Tras el primer error puedes revisar las evidencias antes de responder.</p></div></div><small>REINTENTAR INICIA UNA PARTIDA NUEVA; EL RESULTADO ANTERIOR SE CONSERVA.</small></article>
      <article className="surface-card"><div className="panel-heading yellow"><Icon name="trophy" /><h3>Rangos &amp; pompones</h3></div><p>La suma de tus puntuaciones guardadas determina tu rango en la agencia. Cada respuesta correcta añade 200 puntos.</p><ul className="rank-list">{ranks.map(([name,points,color]) => <li key={name}><span><b className={color}>●</b> {name}</span><small className={color}>{points}</small></li>)}</ul></article>
    </div></section>
    <section className="surface-card station-anatomy"><span className="eyebrow yellow">VISTA DE MANDO / DIORAMA DE CABINA</span><h2>Anatomía de la estación de trabajo</h2><div className="anatomy-grid"><div><small className="cyan">EXPEDIENTES</small><p>▱ correo_sospechoso.eml</p><p>▱ cabeceras_del_mensaje</p><p>▱ enlace_señuelo</p></div><div><small className="cyan">VISOR FORENSE</small><pre>DE: support@bank-security.example{'\n'}SPF: fail / DKIM: none{'\n'}COMPARAR: banco.neo.example</pre><small>Inspecciona cada dato y conserva la evidencia.</small></div><div><small className="lavender">RESOLUCIÓN FINAL</small><p>Selecciona una conclusión.</p><p>Confirma tu deducción.</p><span className="tag cyan">CONTRASTA ANTES DE ACTUAR</span></div></div></section>
    <section className="tutorial-banner surface-card"><img src={tutorial} alt="Rex invita al detective a su primera misión." /><div><span className="eyebrow">TRANSMISIÓN DIRECTA // DETECTIVE REX</span><h2>¿Listo para tu primera asignación?</h2><p>El sospechoso ha enviado un correo a los servidores de la agencia. Sigue los seis pasos y preserva los datos de Neo-Pangea.</p></div><Link className="button purple" to="/case/001"><Icon name="search" /> Iniciar caso tutorial (caso #001)</Link></section>
  </main>
}
