const fs = require('node:fs')
const path = require('node:path')
const jsonServer = require('json-server')
const target = path.join(__dirname, '.tmp', 'db.json')
fs.mkdirSync(path.dirname(target), { recursive: true })
fs.copyFileSync(path.join(__dirname, '..', 'db.json'), target)
const server = jsonServer.create()
server.use(jsonServer.defaults({ logger: false }))
server.use(jsonServer.bodyParser)
server.use(jsonServer.router(target))
server.listen(3002, '127.0.0.1')
